### ISSUE TITLE
Using metro + react native highcharts webview, not rendered on ios

### ISSUE THREAD

**Issue by newbster1** [fattomhk/react-native-highcharts-wrapper#1]
On ios device i still get same error as the one form highchart react natve package, is there a work around for this?

Would really appreciate it as highchart react native is no longer actively maintained so thought if you can help.

**Comment by newbster1** [comment]
Also i noticed this error : ```atal error: module map file '/Users/akhilkillawala/Documents/Github/mma-ios-dashboard/ios/DerivedData/Billboard/Build/Products/Release-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap' not found``` so is it compatible with only expo and not with metro?

**Comment by newbster1** [comment]
How to use dark theme for ios ?
I am unable to use it when enable styled mode or overiding dark colors

**Comment by horstleung** [comment]
> On ios device i still get same error as the one form highchart react natve package, is there a work around for this?
> 
> Would really appreciate it as highchart react native is no longer actively maintained so thought if you can help.

Would check it later.

**Comment by horstleung** [comment]
> Also i noticed this error : `atal error: module map file '/Users/akhilkillawala/Documents/Github/mma-ios-dashboard/ios/DerivedData/Billboard/Build/Products/Release-iphoneos/ExpoModulesCore/ExpoModulesCore.modulemap' not found` so is it compatible with only expo and not with metro?

Related to expo lib setup.

**Comment by horstleung** [comment]
> How to use dark theme for ios ? I am unable to use it when enable styled mode or overiding dark colors

would you provide a screenshot? what is the expected result?

**Comment by horstleung** [comment]
> 

I made a setOptions to 
`colors: ['#2b908f', '#90ee7e', '#f45b5b', '#7798BF', '#aaeeee', '#ff0066',
        '#eeaaee', '#55BF3B', '#DF5353', '#7798BF', '#aaeeee'],
    chart: {
        backgroundColor: {
            linearGradient: { x1: 0, y1: 0, x2: 1, y2: 1 },
            stops: [
                [0, '#2a2a2b'],
                [1, '#3e3e40']
            ]
        },
        style: {
            fontFamily: '\'Unica One\', sans-serif'
        },
        plotBorderColor: '#606063'
    },
    title: {
        style: {
            color: '#E0E0E3',
            textTransform: 'uppercase',
            fontSize: '20px'
        }
    },
    subtitle: {
        style: {
            color: '#E0E0E3',
            textTransform: 'uppercase'
        }
    },
    xAxis: {
        gridLineColor: '#707073',
        labels: {
            style: {
                color: '#E0E0E3'
            }
        },
        lineColor: '#707073',
        minorGridLineColor: '#505053',
        tickColor: '#707073',
        title: {
            style: {
                color: '#A0A0A3'
            }
        }
    },
    yAxis: {
        gridLineColor: '#707073',
        labels: {
            style: {
                color: '#E0E0E3'
            }
        },
        lineColor: '#707073',
        minorGridLineColor: '#505053',
        tickColor: '#707073',
        tickWidth: 1,
        title: {
            style: {
                color: '#A0A0A3'
            }
        }
    },
    tooltip: {
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        style: {
            color: '#F0F0F0'
        }
    },
    plotOptions: {
        series: {
            dataLabels: {
                color: '#F0F0F3',
                style: {
                    fontSize: '13px'
                }
            },
            marker: {
                lineColor: '#333'
            }
        },
        boxplot: {
            fillColor: '#505053'
        },
        candlestick: {
            lineColor: 'white'
        },
        errorbar: {
            color: 'white'
        }
    },
    legend: {
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        itemStyle: {
            color: '#E0E0E3'
        },
        itemHoverStyle: {
            color: '#FFF'
        },
        itemHiddenStyle: {
            color: '#606063'
        },
        title: {
            style: {
                color: '#C0C0C0'
            }
        }
    },
    credits: {
        style: {
            color: '#666'
        }
    },
    labels: {
        style: {
            color: '#707073'
        }
    },
    drilldown: {
        activeAxisLabelStyle: {
            color: '#F0F0F3'
        },
        activeDataLabelStyle: {
            color: '#F0F0F3'
        }
    },
    navigation: {
        buttonOptions: {
            symbolStroke: '#DDDDDD',
            theme: {
                fill: '#505053'
            }
        }
    },
    // scroll charts
    rangeSelector: {
        buttonTheme: {
            fill: '#505053',
            stroke: '#000000',
            style: {
                color: '#CCC'
            },
            states: {
                hover: {
                    fill: '#707073',
                    stroke: '#000000',
                    style: {
                        color: 'white'
                    }
                },
                select: {
                    fill: '#000003',
                    stroke: '#000000',
                    style: {
                        color: 'white'
                    }
                }
            }
        },
        inputBoxBorderColor: '#505053',
        inputStyle: {
            backgroundColor: '#333',
            color: 'silver'
        },
        labelStyle: {
            color: 'silver'
        }
    },
    navigator: {
        handles: {
            backgroundColor: '#666',
            borderColor: '#AAA'
        },
        outlineColor: '#CCC',
        maskFill: 'rgba(255,255,255,0.1)',
        series: {
            color: '#7798BF',
            lineColor: '#A6C7ED'
        },
        xAxis: {
            gridLineColor: '#505053'
        }
    },
    scrollbar: {
        barBackgroundColor: '#808083',
        barBorderColor: '#808083',
        buttonArrowColor: '#CCC',
        buttonBackgroundColor: '#606063',
        buttonBorderColor: '#606063',
        rifleColor: '#FFF',
        trackBackgroundColor: '#404043',
        trackBorderColor: '#404043'
    }`

and get a result:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/1083049/184476377-07eeafaa-d994-44f2-a4e3-15cdba8f7ad8.png">

**Comment by horstleung** [comment]
> > On ios device i still get same error as the one form highchart react natve package, is there a work around for this?
> > Would really appreciate it as highchart react native is no longer actively maintained so thought if you can help.
> 
> Would check it later.

I have just created a bare rn project and do the setup, it just works.
